export const GET_WEATHER_FROM_COORDS = 'GET_WEATHER_FROM_COORDS';
export const GET_LOCATIONLIST_FROM_INPUT = 'GET_LOCATIONLIST_FROM_INPUT'
export const GET_LOCATION_FROM_COORDS = 'GET_LOCATION_FROM_COORDS'
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_ALERT = 'SET_ALERT';

